/* The following code was generated by JFlex 1.6.1 */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Alexsandro/Documents/UFPE/5º período/Compiladores/Exercício 1 - Analizador Léxico/Compiladores-Exercicio-1/MiniJava.jflex</tt>
 */
class MiniJavaLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\56\1\2\1\2\22\0\1\1\1\43\4\0"+
    "\1\40\1\0\1\50\1\51\1\37\1\44\1\47\1\45\1\32\1\36"+
    "\1\35\11\34\1\0\1\46\1\41\1\42\3\0\22\33\1\23\7\33"+
    "\1\54\1\0\1\55\1\0\1\33\1\0\1\7\1\3\1\11\1\20"+
    "\1\6\1\30\1\25\1\27\1\15\2\33\1\5\1\22\1\10\1\4"+
    "\1\13\1\33\1\24\1\12\1\17\1\14\1\21\1\26\1\16\1\31"+
    "\1\33\1\52\1\0\1\53\7\0\1\56\u1fa2\0\1\56\1\56\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\20\3\1\4\2\5\1\1\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\11\3"+
    "\1\25\11\3\2\0\1\26\1\27\1\30\16\3\1\31"+
    "\3\0\7\3\2\0\1\32\6\3\2\0\1\3\43\0"+
    "\1\25\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\57\0\u034e\0\57\0\u037d\0\57"+
    "\0\u03ac\0\57\0\u03db\0\u040a\0\57\0\57\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\u0439"+
    "\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1"+
    "\0\215\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\57\0\57\0\57\0\u07e5"+
    "\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\57\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0c7c\0\57\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67"+
    "\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf"+
    "\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057"+
    "\0\u1086\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf"+
    "\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347"+
    "\0\u1376\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490\0\57"+
    "\0\u14bf\0\u14ee\0\u151d\0\u154c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\5\1\10"+
    "\1\11\1\12\1\13\1\5\1\14\1\5\1\15\1\5"+
    "\1\16\1\17\1\20\1\21\1\5\1\22\1\5\1\23"+
    "\1\5\1\24\1\5\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\62\0\1\5"+
    "\1\50\25\5\1\0\3\5\24\0\27\5\1\0\3\5"+
    "\24\0\3\5\1\51\23\5\1\0\3\5\24\0\2\5"+
    "\1\52\10\5\1\53\13\5\1\0\3\5\24\0\3\5"+
    "\1\54\23\5\1\0\3\5\24\0\2\5\1\55\24\5"+
    "\1\0\3\5\24\0\14\5\1\56\12\5\1\0\3\5"+
    "\24\0\11\5\1\57\15\5\1\0\3\5\24\0\5\5"+
    "\1\60\17\5\1\61\1\5\1\0\3\5\24\0\21\5"+
    "\1\62\2\5\1\63\2\5\1\0\3\5\24\0\1\5"+
    "\1\64\25\5\1\0\3\5\24\0\4\5\1\65\22\5"+
    "\1\0\3\5\24\0\14\5\1\66\11\5\1\67\1\0"+
    "\3\5\24\0\3\5\1\70\23\5\1\0\3\5\24\0"+
    "\24\5\1\71\2\5\1\0\3\5\24\0\4\5\1\72"+
    "\22\5\1\0\3\5\55\0\2\25\57\0\1\73\1\74"+
    "\57\0\1\75\60\0\1\76\56\0\1\77\17\0\1\5"+
    "\1\100\25\5\1\0\3\5\24\0\5\5\1\101\21\5"+
    "\1\0\3\5\24\0\7\5\1\102\17\5\1\0\3\5"+
    "\24\0\14\5\1\103\12\5\1\0\3\5\24\0\23\5"+
    "\1\61\3\5\1\0\3\5\24\0\4\5\1\104\22\5"+
    "\1\0\3\5\24\0\4\5\1\105\22\5\1\0\3\5"+
    "\24\0\1\106\26\5\1\0\3\5\24\0\14\5\1\61"+
    "\12\5\1\0\3\5\24\0\11\5\1\102\15\5\1\0"+
    "\3\5\24\0\12\5\1\107\14\5\1\0\3\5\24\0"+
    "\12\5\1\110\14\5\1\0\3\5\24\0\12\5\1\111"+
    "\14\5\1\0\3\5\24\0\21\5\1\112\5\5\1\0"+
    "\3\5\24\0\7\5\1\113\17\5\1\0\3\5\24\0"+
    "\14\5\1\114\12\5\1\0\3\5\24\0\12\5\1\115"+
    "\14\5\1\0\3\5\24\0\2\5\1\52\24\5\1\0"+
    "\3\5\22\0\1\73\1\116\20\73\1\117\6\73\1\0"+
    "\3\73\22\0\22\74\1\120\6\74\1\0\3\74\1\0"+
    "\1\121\22\0\2\5\1\122\24\5\1\0\3\5\24\0"+
    "\22\5\1\123\4\5\1\0\3\5\24\0\3\5\1\61"+
    "\23\5\1\0\3\5\24\0\3\5\1\124\23\5\1\0"+
    "\3\5\24\0\7\5\1\107\17\5\1\0\3\5\24\0"+
    "\14\5\1\125\12\5\1\0\3\5\24\0\2\5\1\125"+
    "\24\5\1\0\3\5\24\0\7\5\1\61\17\5\1\0"+
    "\3\5\24\0\15\5\1\61\11\5\1\0\3\5\24\0"+
    "\5\5\1\61\21\5\1\0\3\5\24\0\12\5\1\126"+
    "\14\5\1\0\3\5\24\0\14\5\1\127\12\5\1\0"+
    "\3\5\24\0\11\5\1\130\15\5\1\0\3\5\24\0"+
    "\2\5\1\102\24\5\1\0\3\5\22\0\1\73\1\116"+
    "\20\73\1\117\5\73\1\131\1\0\3\73\22\0\22\74"+
    "\1\120\5\74\1\132\1\0\3\74\1\0\1\121\55\0"+
    "\1\133\23\0\3\5\1\134\23\5\1\0\3\5\24\0"+
    "\14\5\1\135\12\5\1\0\3\5\24\0\5\5\1\136"+
    "\21\5\1\0\3\5\24\0\12\5\1\137\14\5\1\0"+
    "\3\5\24\0\5\5\1\140\21\5\1\0\3\5\24\0"+
    "\3\5\1\141\23\5\1\0\3\5\24\0\21\5\1\111"+
    "\5\5\1\0\3\5\22\0\1\73\1\116\7\73\1\142"+
    "\10\73\1\117\6\73\1\0\3\73\22\0\11\74\1\143"+
    "\10\74\1\120\6\74\1\0\3\74\1\0\1\121\22\0"+
    "\4\5\1\111\22\5\1\0\3\5\24\0\24\5\1\61"+
    "\2\5\1\0\3\5\24\0\15\5\1\107\11\5\1\0"+
    "\3\5\24\0\6\5\1\61\20\5\1\0\3\5\24\0"+
    "\22\5\1\61\4\5\1\0\3\5\24\0\17\5\1\144"+
    "\7\5\1\0\3\5\22\0\1\73\1\116\14\73\1\145"+
    "\3\73\1\117\6\73\1\0\3\73\22\0\16\74\1\146"+
    "\3\74\1\120\6\74\1\0\3\74\1\0\1\121\22\0"+
    "\27\5\1\147\3\5\22\0\1\73\1\116\3\73\1\150"+
    "\14\73\1\117\6\73\1\0\3\73\22\0\5\74\1\151"+
    "\14\74\1\120\6\74\1\0\3\74\1\0\1\121\23\0"+
    "\1\152\53\0\1\73\1\116\17\73\1\153\1\117\6\73"+
    "\1\0\3\73\22\0\21\74\1\154\1\120\6\74\1\0"+
    "\3\74\1\0\1\121\33\0\1\155\43\0\1\73\1\116"+
    "\20\73\1\117\6\73\1\156\3\73\22\0\22\74\1\120"+
    "\6\74\1\157\3\74\1\0\1\121\36\0\1\160\43\0"+
    "\1\161\56\0\1\162\104\0\1\163\40\0\1\164\56\0"+
    "\1\165\55\0\1\166\62\0\1\167\56\0\1\170\63\0"+
    "\1\171\64\0\1\172\56\0\1\173\41\0\1\174\54\0"+
    "\1\175\56\0\1\176\53\0\1\177\72\0\1\200\56\0"+
    "\1\201\51\0\1\202\54\0\1\203\56\0\1\204\46\0"+
    "\1\205\61\0\1\206\56\0\1\207\56\0\1\210\65\0"+
    "\1\211\56\0\1\212\44\0\1\213\56\0\1\214\61\0"+
    "\1\73\56\0\1\74\46\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5499];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\20\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\2\1\13\11\23\1\2\0\3\11\16\1"+
    "\1\11\3\0\7\1\2\0\1\11\6\1\2\0\1\1"+
    "\43\0\1\11\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
int qtdeID=0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MiniJavaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    System.out.println("Quantidade de Identificadores encontrados: "+qtdeID);

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caractere ilegal! '" + yytext() + "' na linha: " + yyline + ", coluna: " + yycolumn);
            }
          case 27: break;
          case 2: 
            { /* Ignorando o whitespace */
            }
          case 28: break;
          case 3: 
            { qtdeID++; System.out.println("Identificador "+yytext());
            }
          case 29: break;
          case 4: 
            { System.out.println("Token .");
            }
          case 30: break;
          case 5: 
            { System.out.println("Inteiro: "+yytext());
            }
          case 31: break;
          case 6: 
            { System.out.println("Operador *");
            }
          case 32: break;
          case 7: 
            { System.out.println("Operador <");
            }
          case 33: break;
          case 8: 
            { System.out.println("Token =");
            }
          case 34: break;
          case 9: 
            { System.out.println("Operador !");
            }
          case 35: break;
          case 10: 
            { System.out.println("Operador +");
            }
          case 36: break;
          case 11: 
            { System.out.println("Operador -");
            }
          case 37: break;
          case 12: 
            { System.out.println("Token ;");
            }
          case 38: break;
          case 13: 
            { System.out.println("Token ,");
            }
          case 39: break;
          case 14: 
            { System.out.println("Token (");
            }
          case 40: break;
          case 15: 
            { System.out.println("Token )");
            }
          case 41: break;
          case 16: 
            { System.out.println("Token {");
            }
          case 42: break;
          case 17: 
            { System.out.println("Token }");
            }
          case 43: break;
          case 18: 
            { System.out.println("Token [");
            }
          case 44: break;
          case 19: 
            { System.out.println("Token ]");
            }
          case 45: break;
          case 20: 
            { System.out.print(yytext());
            }
          case 46: break;
          case 21: 
            { System.out.println("Palavra reservada: "+yytext());
            }
          case 47: break;
          case 22: 
            { System.out.println("Operador &&");
            }
          case 48: break;
          case 23: 
            { System.out.println("Operador ==");
            }
          case 49: break;
          case 24: 
            { System.out.println("Operador !=");
            }
          case 50: break;
          case 25: 
            { System.out.println("ComentÃ¡rio de linha: "+yytext());
            }
          case 51: break;
          case 26: 
            { System.out.println("ComentÃ¡rio multi linha: "+yytext());
            }
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java MiniJavaLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        MiniJavaLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new MiniJavaLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
